### ISSUE TITLE
Different behaviour based on the Appender type

### ISSUE THREAD

**Issue by ebenini-mdsol** [kamon-io/kamon-logback#28]
Hi there,
I attach in here a simple project we crafted at work that shows how we get different output based on the appender type `FileAppender` and `AsyncAppender` into the `logback`.

If you take the project and do an `sbt run` changing the value of `appender-ref` (line 25) once with `FILE` and then with `ASYNCFILE` you can see that the `log/app.log` in one case just returns empty and the other it prints the span `operationName`.

We guess it can be due to some bugs into the `kamon-logback` or the `kanela-agent`.
Could you please have a look at the code and let us know?
Thank you so much

[example_project_kamon_logback_async.zip](https://github.com/kamon-io/kamon-logback/files/3606670/example_project_kamon_logback_async.zip)

**Comment by jatcwang** [comment]
repro project on github: https://github.com/jatcwang/kamon-logback-bug-repro

**Comment by ivantopo** [comment]
Hey @jatcwang @ebenini-mdsol, I was trying to run this and reproduce the issue but Logback is failing to initialize because the `HumanCirceCustomDataLayout` and `CirceMdsolLogLayout` classes are missing. Are those completely necessary for reproducing the issue?

**Comment by jatcwang** [comment]
Oops! It shouldn't be. I have updated the repo. Latest master should show the issue cheers!

**Comment by ivantopo** [comment]
Folks, after testing the code above a bit, there are a couple observations from it:
  - First, calling `Kamon.init()` will only attach the instrumentation if the kamon-bundle is on the classpath, which is not the case here. It was a bit weird to figure it out because the layout you guys are using is not including the actual messages on the file, but you should be seeing a `Failed to attach the instrumentation because the Kamon Bundle is not present on the classpath` message in the logs.
  - Second, for some reason that I can't figure out just yet, the instrumentation that sets the Context for the AsyncAppender is working fine when the application starts with -javaagent but not with Kamon.init(). I just raised https://github.com/kamon-io/kamon-logback/pull/29 to fix that issue and should release it at some point during the weekend.

In your case, if you just start your app with -javaagent:/path/to/kanela.jar it should work! Also, you guys might want to keep an eye on this PR: https://github.com/kamon-io/kamon-bundle/pull/2

**Comment by jatcwang** [comment]
That's great @ivantopo thanks for looking into it! 😄 

Yes our actual app does has kamon-bundle but I missed that when writing the minimal reproduction. Glad that you've found a fix for the issue.
